services:
  gallery-spring:
    build: .
    env_file:
      - .env
    environment:
      DB_URL: jdbc:mysql://gallery-mysql:3306/gallery
      REDIS_URL: gallery-redis  # Redis URL 환경 변수 추가
    depends_on:
      - gallery-mysql
      - gallery-redis
    ports:
      - "${LOCAL_SERVER_PORT}:8080"
  gallery-mysql:
    image: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: gallery
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - gallery-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      retries: 10
  gallery-redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10

volumes:
  gallery-mysql-data:
